### DISCUSSION TITLE
sceptre 1.x -> 2.x conversion for a custom resolver

### DISCUSSION THREAD

**Discussion by JeffHailer-MRM** [cloudreach/sceptre#1074] [Q&A] [answered]
python newbie here ...

I inherited a sceptre 1.x repo that I am converting to sceptre 2.x.
The 1.x repo has a custom resolver that accepts a jinja formatted file for AWS instance user data.

Here's the original:
"file_as_template.py"
```
from sceptre.resolvers import Resolver
from jinja2 import Template

class FileAsTemplate(Resolver):

    def __init__(self, *args, **kwargs):
        super(FileAsTemplate, self).__init__(*args, **kwargs)

    def resolve(self):
        try:
            with open(self.argument, "r") as file:
                data = file.read()
                template = Template(data)
                template_data = self.stack_config['template_data']
                return template.render(**template_data)
        except (EnvironmentError, TypeError) as e:
            raise e
```
The above throws :

> AttributeError: 'FileAsTemplate' object has no attribute 'stack_config'

Assuming that hooks and resolvers are similar, I tried to apply learnings from https://github.com/Sceptre/sceptre/issues/684 but I'm not having any success.

JIC it matters, here's my setup.py:
```
from setuptools import setup

setup(
    name='file-as-template-resolver',
    py_modules=['file_as_template'],
    entry_points={
        'sceptre.resolvers': [
            'file_as_template = file_as_template:FileAsTemplate',
        ],
    }
)
```

Any assistance would be greatly appreciated.

**Comment by zaro0508** [comment]
I think you are referring to the https://github.com/lukeplausin/sceptre-template-resolver @himmelmrm?  if so i think the new [sceptre-file-resolver](https://sceptre.cloudreach.com/dev/docs/resolvers.html#file) can accomplish the same use case and it's included in sceptre ver 2.6.1

**Reply by JeffHailer-MRM** [reply]
Thanks for the reply.
Custom resolver "file_as_template" was created to allow EC2 userdata to be templatized.  It's used like this in a troposphere template:
```
template_path: ec2/instances.py
template_data:
  cloudinit_data:
   hostname: prod-lampdemo-aws01
   fqdn: prod-lampdemo-aws01.demo.client.com
sceptre_user_data:
  UserData: !file_as_template config/lampdemo/prod/ud-combined.j2


```
