### DISCUSSION TITLE
Jinja support in templates

### DISCUSSION THREAD

**Discussion by brian-provenzano** [cloudreach/sceptre#1095] [Q&A]
I'm fairly new to sceptre and I was wondering what is supported in jinja templates?  Can we do things like "includes", looping etc or is it just limited to referencing sceptre_user_data?

`{{ sceptre_user_data.something }}`  this works OK

`{{ include('user-data.sh')|indent(6) }}`  is this supported?  I couldnt get this to work. I was trying to reference a script as an external resource similar to terraform

I also tried this syntax:
`{% include 'userdata.sh' %}`

This is the reference I am using
http://jinja.pocoo.org/docs/2.10/templates/

It could be I have a general misunderstanding of jinja and sceptre as well.  If so, forgive my stupid question :)

Also, I'm not sure if this is the best place to ask questions like this - I don't want to pollute the issue tracker with general product function questions if I dont have to.  Is there another methods?  Slack channel etc?

**Comment by 1oglop1** [comment]
@brian-provenzano Yes colleague of mine ran into same issue where we found out that many directives are not supported like `include` or `extends` etc.. 
As a workaround we ended up with custom resolver - which is not very practical solution.

@niallgrantcloudreach - I already discussed it on CR slack and Juan said it was for security reason, which I believe is not valid argument since sceptre is leveraging `jinja` it should support all functionality or clearly state why certain things do not work.

custom resolver usage:
```yaml
template_path: external-templates/directoryservice/cognito_userpool.py
sceptre_user_data:
  user-pools:
    SuperPool{{ environment_config.account_name | title}}{{ environment_config.short_region | title}}CognitoUserPool:
      schema:
        !jinja_include files/cognito/user-pool/schema.j2.yaml
```

Resolver code:
```python
# -*- coding: utf-8 -*-
import os

import yaml
from sceptre.resolvers import Resolver
from jinja2 import Environment, FileSystemLoader


class JinjaInclude(Resolver):
    """
    Resolver for getting the contents of a file which would work as a jinja include

    :param argument: Absolute path to file.
    :type argument: str
    """

    def __init__(self, *args, **kwargs):
        super(JinjaInclude, self).__init__(*args, **kwargs)

    def resolve(self):
        """
        Retrieves the contents of a file at a given absolute file path.

        :returns: Contents of file resolved by jinja using sceptre namespace
        :rtype: dict
        """
        try:
            path, filename = os.path.split(self.argument)
            render_result = Environment(
                loader=FileSystemLoader(path)
            ).get_template(filename).render({
                "environment_config": self.environment_config
            })
            return yaml.safe_load(render_result)
        except (EnvironmentError, TypeError) as e:
            raise e
```
