### DISCUSSION TITLE
Document least-privilege IAM permissions and bucket creation

### DISCUSSION THREAD

**Discussion by rdkr** [cloudreach/sceptre#1200] [Q&A]
It would be useful to have documentation about running Sceptre in a least-privilege environment in the Getting Started guide. Specifically, it would be useful to explain:

* a bucket will be automatically created, or that you can specify one which you have created
* the least-privilege IAM permissions for a specified bucket
* any other least-privilege IAM permissions needed to run Sceptre (probably just Cloudformation)

Working on this earlier, this should be a start towards the IAM permissions, but `cloudformation:*` may be excessive:

```
PolicyDocument:
  Version: 2012-10-17
  Statement:
    -
      Effect: Allow
      Resource: "*"
      Action:
        - cloudformation:*
    -
      Effect: Allow
      Resource: <bucket>/*
      Action:
        - s3:PutObject
        - s3:GetObject
    -
      Effect: Allow
      Resource: <bucket>
      Action:
        - s3:ListBucket
```
