### DISCUSSION TITLE
Ref SecuityGroup id's that will be created by the template in yaml config ?

### DISCUSSION THREAD

**Discussion by aduzsardi** [cloudreach/sceptre#627] [Q&A]
Hi,
I would like to define all the securitygroup rules in a config file for a stack , the problem is that beside the regular cidr,ports allow/deny rules i would like to also add the rules that will reference the security groups that will be created by this stack/template.

Is this possible ?

i.e.
```
rules:
- IpProtocol: "tcp"
  FromPort: "80"
  ToPort: "80"
  CidrIp: "10.0.0.0/8"
- IpProtocol: "tcp"
  FromPort: "80"
  ToPort: "80"
  SourceSecurityGroupId: Ref security group that will be created by the template/stack
```
is this possible with sceptre configs ?

Thank you!

**Comment by 1oglop1** [comment]
This depends on your template, but it is possible to write template using python and `troposphere` to do so. All you need to do is to check for `SourceSecurityGroupId` and then process the reference.

**Comment by aduzsardi** [comment]
The template is python and yes , i know you can reference the security group using troposphere's `Ref` class but i wonder if there's some kind of trick to add the security group that will be created in the stacks's config file instead

let's say have some rules in mystack.yaml
```
template_path:  mystack.py
sceptre_user_data:
  rules:
    - IpProtocol: "tcp"
      FromPort: "80"
      ToPort: "80"
      CidrIp: "10.0.0.0/8"
    - IpProtocol: "tcp"
      FromPort: "80"
      ToPort: "80"
      SourceSecurityGroupId: "my-sec-group-name"
```
i want to iterate over this rules with a `AWS::EC2::SecurityGroupIngress` resource and where `my-sec-group-name` will be created by this template/stack :)

I guess this si probably not possible
