### ISSUE TITLE
Render stack templates as Jinja2 templates

### ISSUE THREAD

**Issue by jjonek** [cloudreach/sceptre#103]
Would be nice to support Jinja2 templating for stack templates in addition to _troposphere_.

I'd find it really useful to make templates more dynamic without having to convert everything into python. Further, new CloudFormation features would be immediately accessible without having to wait for _troposphere_ to get updated.

Example: Create dynamic S3 bucket policy for multiple accounts to write CloudTrail logs into shared bucket:
```
...
          - Sid: 'AWSCloudTrailWrite'
            Effect: 'Allow'
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:PutObject'
            Resource:
            {% for account_id in sceptre_user_data.cloudtrail.accounts %}
            - !Sub 'arn:aws:s3:::${CloudTrailBucket}/AWSLogs/{{ account_id }}/*'
            {% endfor %}
```

**Comment by jamesroutley** [comment]
Yep - this is a really good idea. Let me and @seanrankine have a think about the implementation and we'll get back.

**Comment by jjonek** [comment]
https://github.com/jjonek/sceptre/commit/b691e9ab756e34f9cc85725cbfcf9603dda74c8d would do the trick (and conflict with #92), but I don't mind if you come up with something fancier. Wouldn't hurt to get some more context either, e.g. _environment_path_, _project_code_, etc.

**Comment by jamesroutley** [comment]
Hey @jjonek that looks really good. One point: 

For Troposphere templates, the only data we pass through is the `sceptre_user_data` dict. If a user wants to pass an environment variable through, they would need to set a value in `sceptre_user_data` to the env var they want:

```yaml
template_path: ...
parameters: ...
sceptre_user_data:
  a: b
  c: !environment_variable MY_ENV_VAR
```

I think this is a slightly cleaner model as the user only needs to think about a single data source when writing templates.

What do you think? If you're happy with doing it that way and want to submit a PR I'd happily accept it.
