### ISSUE TITLE
Sceptre init cmd

### ISSUE THREAD

**Issue by jamesroutley** [cloudreach/sceptre#112]
Add an `init` command, to quickly initialise new projects. 

The init command should be able to initialise:

- projects (new `config/` and `templates/` directories)
- environment (new directory with a `config.yaml`)
- stack (new `<name>.yaml`)

Files should contain example data, with optional parameters commented out:

```yaml
project_code: prj
region: us-east-1
# iam_role: aws:arn...
# template_bucket_name: my_sceptre_templates
...
```
