### ISSUE TITLE
Project variables single value access

### ISSUE THREAD

**Issue by dnedbaylo** [cloudreach/sceptre#115]
Hi guys,

Is there any way to access a single value from project variables file?

E.g. the following effectively returns dictionary:

```
parameters:
  adminEmail: !project_variables /emails.yaml
```

for the stack called `notifications` and environment called `dev`:

```
dev:
  notifications:
    admin_email: 'admin@example.com'
    support_email: 'support@example.com'
```
