### ISSUE TITLE
Make environment config variables available in jinja templating of stack configs

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#150]
It would be handy to be able to reference environment config variables within Jinja templating of stack configs.

For example:
```yaml
--- #config.yaml 
region: eu-west-1

--- #stack.yaml 
parameters:
    BucketName: example-bucket-{{ config.region }}
```
