### ISSUE TITLE
Stack id doesn't exist for dependent stack

### ISSUE THREAD

**Issue by wesleywh** [cloudreach/sceptre#181]
# Background
I'm very new to sceptre and still attempting to get things to work. 

As far as I understand it if I make a dependency using the `!stack_output` parameter it should make sure that stack exists (make it) prior to continuing if it doesn't already exist.
Does this make it create the stack then import the dependency to the current stack I am trying to create or is this not intended functionality?

If this isn't the case please set me straight.

However, I just get an error that states `Stack with id <id> does not exist`.

# Project structure
```
|--sceptre
   |--config
      |--test
          |--config.yaml
          |--server.yaml
          |--winstack.yaml
   |--templates
      |--xva-stack.yaml
      |--xva-server.yaml
```
Note: All the yaml files have been tested and build fine by themselves.

# Debug
## Command Ran
```
cd /sceptre
sceptre --var environment=test --var region=us-east-1 --var uniqueid=manual launch-stack test server
```
## Command Output
```
sceptre.stack - test/server - Launching stack
sceptre.stack - test/server - Stack is in the PENDING state
sceptre.stack - test/server - Creating stack
Stack with id xva-test-manual-winstack does not exist
```
Note: The full debug log states it is able to use my aws credentials and setup a boto3 session fine.

## Expected Output
Successful deployment of `xva-stack.yaml` and `xva-server.yaml` to cloudformation.

# Config Files
## config.yaml
```
project_code: "xva"
region: {{ var.region | default("us-east-1") }}
template_bucket_name: {{ var.bucket_name | default("my-bucket") }}
```
## winstack.yaml
```
template_path: templates/xva-stack.yaml
stack_name: xva-{{ var.environment }}-{{ var.uniqueid }}-winstack
parameters:
  environment: {{ var.environment }}
  uniqueid: {{ var.uniqueid }}
```
Output
```
Outputs:
  Sceptre:
    Description: Needed for sceptre dependency linking
    Export:
      Name: !Sub '${AWS::StackName}-stackname'
    Value: !Sub '${AWS::StackName}'
```
Note: This yaml file (`templates/xva-stack.yaml`) is outputting a "Sceptre" value that is a dependency of `server.yaml`
## server.yaml
```
template_path: ../templates/xva-calcserver.yaml
stack_name: xva-{{ var.environment }}-{{ var.uniqueid }}-server
parameters:
  environment: {{ var.environment }}
  uniqueid: {{ var.uniqueid }}
  instanceSize: {{ var.size | default("t2.medium") }}
  CFOpsworksStack: !stack_output {{ var.uniqueid }}-winstack::Sceptre
```

I really didn't know where else to post a question like this. Am I doing something wrong here, is this intended behavior?
