### ISSUE TITLE
Add support for Stack Notifications

### ISSUE THREAD

**Issue by georgealton** [cloudreach/sceptre#184]
It's possible to configure a Cloud Formation Stack to notify an SNS Topic of events. This is useful for providing monitoring back to teams when a stack is updated. We use this feature, to get Notifications back into Slack for Cloud Formation Events. So I'd like to be able to configure per stack, a list of SNS Notification ARNs in sceptre. 

This could be implemented by adding a property to a stack within sceptre for notifications, followed by the list of Topic ARNs. When the API call is made to AWS to create the stack, the supplied ARNs would be passed, along with other stack parameters.

**Comment by theseanything** [comment]
Yup agree - and feel this could be easily implemented.
So we'd have something like this:
```yaml
template_path: to/some/file.yaml
notifications:
    - arn:aws:sns:us-west-2:111122223333:MyTopic
    - arn:aws:sns:us-west-2:111122223333:MyOtherTopic
    - arn:aws:sns:us-west-2:111122223333:AnotherTopic 
```
And the list is simply passed to relevant API calls.
