### ISSUE TITLE
Dependencies need to be prefixed with environment name

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#187]
According to docs and comments from maintainers, if I have project
```yaml
config/
- config.yaml
- my-env/
  - first.yaml
  - second.yaml
      template_path: templates/second.yaml
      dependencies:
        - first
- templates/
  - first.yaml
  - second.yaml
```

Then `first` should be deployed before `second`. However, this (`sceptre launch-env my-env`) does not work (no error message is seen - the stacks launch successfully, but are instantiated in parallel).
EDIT2: the following does work:
```yaml
config/
- config.yaml
- my-env/
  - first.yaml
  - second.yaml
      template_path: templates/second.yaml
      dependencies:
        - my-env/first
- templates/
  - first.yaml
  - second.yaml
```
.

Would be great if this could be fixed, or docs updated at the very least.
