### ISSUE TITLE
Add before_launch and after_launch hooks

### ISSUE THREAD

**Issue by cboss24** [cloudreach/sceptre#208]
Currently we have lambda code that needs to be zipped and uploaded on each `launch-env` run. This should happen when the lambda stack is created, updated, or if no updates are performed. It would be elegant to use hooks to trigger this side effect. I expected the following to work:

```yaml
hooks:
  after_update:
    - !bundle_upload_lambda
  after_create:
    - !bundle_upload_lambda
```

However, this does not trigger when there are no updates to perform. What do you think about adding the ability to hook on on the `launch` command to guarantee that a hook will be triggered regardless of the work performed on the stack?
