### ISSUE TITLE
Any kind of loops possible?

### ISSUE THREAD

**Issue by ivanilves** [cloudreach/sceptre#331]
First, thanks for the `sceptre`. Awesome tool!

Second, sorry, but I may ask one vague question:

Trying to figure out how could I pass (or iterate over) a list of source security groups in `AWS::EC2::SecurityGroupIngress` definition. I want to have something like this in config

```
parameters:
  ListOfSecurityGroups:
    - sg-abcabcd1
    - sg-abcabcd2
    - sg-abcabcd3
```
and something like this in the template
```
  SomeSecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
      Properties:
      GroupId: !Ref SomeSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref ListOfSecurityGroups
```

The problem is that I can not pass anything but the single SG ID as a plain string into the `SourceSecurityGroupId` field.

### And the question is:
Is there any way to "iterate" over a variable array of string security group IDs within the sceptre template?

Well, if it is not possible, I even could try to implement it myself, if it has some interest for sceptre community.

Thanks!
