### ISSUE TITLE
Defining numbers via `--var-file`

### ISSUE THREAD

**Issue by gbegher** [cloudreach/sceptre#345]
It seems that defining numbers in a variable file is not possible.

Here's the related code.

Content of `variables.yaml`:
```
EcsCluster:
  InstanceType: t2.small
  Size: (*)
```

Content of `ecs-cluster.yaml`:
```
template_path: templates/environment/ecs-cluster.cf.yaml

parameters:
  InstanceType: {{ var.EcsCluster.InstanceType }}
  ClusterSize: {{ var.EcsCluster.Size }}
```

I tried substituting `(*)` with both `1` and `"1"` but neither works.

The result is always:

```
Invalid type for parameter Parameters[2].ParameterValue, value: 1, type: <class 'int'>, valid types: <class 'str'>
```

**Comment by jerep6** [comment]
Hi
Do you tried?
(note the quotes around the variable "ClusterSize")

```
template_path: templates/environment/ecs-cluster.cf.yaml

parameters:
  InstanceType: {{ var.EcsCluster.InstanceType }}
  ClusterSize: "{{ var.EcsCluster.Size }}"
```
