### ISSUE TITLE
Stack with id  does not exist

### ISSUE THREAD

**Issue by ismFerDev** [cloudreach/sceptre#39]
Hi,

I have this directory structure:
```
config/
├── infrastructure
│   ├── config.yaml
│   ├── eni.yaml
│   ├── infrastructure.yaml
│   └── security.yaml

```
and eni.yaml file has this content:
```
template_path: templates/infrastructure/enis.json
stack_name: eni
parameters:
  ManagementSecurityGroup: "{{ var.management_security_group }}"
  SecurityGroup: !stack_output security::InstancesSecurityGroup
  Subnets: "{{ var.subnets|join(', ') }}"
  Enis:  "{{ var.enis|join(', ') }}"
```
why have  I this exception?
`stack with id random-infrastructure-security does not exist``
