### ISSUE TITLE
Chain multiple resolvers in stack config to create an AWS list string

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#4]
Add a way to specify multiple resolvers for a single parameter in a stack config. The result should create an AWS CloudFormation compatible list string (`List<String>` such as `"value1,value2,value3"`). This would reduce the need for many separate AWS CloudFormation parameters in a template, which is particularly handy for when using raw AWS CloudFormation templates.

**Comment by theseanything** [comment]
Suggest syntax within stack config is
```yaml
parameters:
    ParameterName: 
     - !resolver_name argument /or value
     - !resolver_name argument /or value
     - .....
```
for example:
```yaml
parameters:
    SecurityGroupIds: 
     - !stack_outputs webservice-sgs::WebSecurityGroupId
     - sg-12345678
     - !environment_variable SECURITY_GROUP_ID
```

**Comment by jamesroutley** [comment]
I think this syntax may introduce an inconsistency:

``` yaml
parameters:
    # resolves to "outputA,outputB"
    ParamA:
         - !stack_output a::A
         - !stack_output b::B
sceptre_user_data:
    # resolves to ["outputA", "outputB"]
    ParamA:
         - !stack_output a::A
         - !stack_output b::B
```

This isn't inherently an issue, but it may be confusing. Is there a way we could make the conversion more explicit?
