### ISSUE TITLE
Fetching AMI IDs from AWS CLI

### ISSUE THREAD

**Issue by fkhokhar** [cloudreach/sceptre#425]
It would be nice to be able to pull AMI IDs from AWS CLI with a custom resolver. Will save time and prevent errors as opposed to doing it manually. Fetching various kinds of Amazon Linux AMI IDs should be a good start.

**Comment by JuanCanham** [comment]
I have a cmd resolver i was going to release with V2 as a separate piece of code, but if this helps unblock you, you can stick this in `resolvers/cmd.py`

```
import os
import subprocess
from sceptre.resolvers import Resolver
from sceptre.hooks.cmd import Cmd


class CmdResolver(Resolver):
    """
    Resolver for running shell commands and returning the value
    :param argument: Name of the environment variable to return.
    :type argument: str
    """

    def resolve(self):
        """
        Runs a command and returns the output as a string
        :returns: Value of the environment variable.
        :rtype: str
        """
        return subprocess.check_output(self.argument, shell=True)
```

**Comment by craighurley** [comment]
Not quite what you asked for, but you can get the latest AMI using AWSs public SSM parameters within your CloudFormation template, e.g.

```yaml
Parameters:
  AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AmiId
```

WARNING: this will replace instances when the AMI is updated and you perform a CloudFormation update.

For a full list of available AMI paths:

```sh
aws ssm get-parameters-by-path --path /aws/service/ami-amazon-linux-latest
aws ssm get-parameters-by-path --path /aws/service/ami-windows-latest
```
