### ISSUE TITLE
How to conditionally add items to a list parameter?

### ISSUE THREAD

**Issue by craighurley** [cloudreach/sceptre#432]
Is it possible to conditionally additional items to a list parameter being passed to a template?

For example... `config/dev/test.yaml`:

```
template_path: templates/test.yaml
stack_tags:
  Application: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  Owner: {{ environment_config.owner }}
parameters:
  VPC: !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::VPC
  PublicSubnets:
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet1
# Conditionally add additional items to the list (based on {{ environment_config.environment }})
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet2
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet3
```

**Comment by akdor1154** [comment]
```
parameters:
  VPC: !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::VPC
  PublicSubnets:
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet1
{% if environment_config.environment == 'something' %}
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet2
    - !stack_output_external {{ environment_config.project_code }}-{{ environment_config.environment }}-network-vpc::PublicSubnet3
{% endif %}
```
?
```
