### ISSUE TITLE
Feature request: variable resolution within self (env and stack config files)

### ISSUE THREAD

**Issue by et304383** [cloudreach/sceptre#466]
Basically, I want to reduce copy/paste of strings.  I'd like to be able to do this:

```
prefix: some string

sceptre_user_data:
  a_value: {{ prefix }}-a
  b_value: {{ prefix }}-b
```
