### ISSUE TITLE
Sceptre launch-stack exits with success even if update fails

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#497]
Sceptre v1.

`sceptre launch-stack env stack` succeeds (exits with code 0) even if the update fails, as long as the update rollback succeeds.

Expected behaviour: sceptre should exit with code > 0 if update fails.

To reproduce:
- Launch an env with this single stack:
  ```yaml
  Resources:
    Bucket00:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sceptre-force-bucket-name
  ```
- Rename `Bucket00` -> `Bucket01` (to force update to fail)
- Run `sceptre launch-stack env bucket`
- Note sceptre exits with code 0. (it should be something nonzero).

`launch-env` in the same scenario seems to behave itself.

This hit us today with a DB update that failed and our CI script continued on anyway...
