### ISSUE TITLE
CAPABILITY_AUTO_EXPAND required for SAM templates

### ISSUE THREAD

**Issue by arcturial** [cloudreach/sceptre#538]
I am trying to create a stack using SAM templates like so:

```
Resources:
  WebhookApi:
    Type: AWS::Serverless::API
    Properties:
      StageName: !Ref StageName
      DefinitionUri: swagger.yml
```
I receive the following message when running it.

`An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_AUTO_EXPAND]`

Are SAM templates not fully supported?
