### ISSUE TITLE
Fix sceptre_user_data with !stack_output

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#558]
In v2.0 When referencing `sceptre_user_data` with a `stack_output` resolver an error occurs where the resolvable property is read Sceptre enters into a recursion and eventually returns a `RecursionError: maximum recursion depth exceeded`.

**Comment by m1keil** [comment]
An easy way to reproduce:

template.yaml
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot

Outputs:
  TestOutput:
    Value: !Ref 'AWS::StackName'
```


config.yaml
```
project_code: testing
region: ap-southeast-2
```

stack1.yaml
```
template_path: template.yaml
```

stack2.yaml
```
template_path: template.yaml
sceptre_user_data:
  # both test & test2 will cause RecursionError
  #test: !stack_output stack1.yaml::TestOutput
  #test2: !stack_output_external testing-stack1::TestOutput
```
