### ISSUE TITLE
Stack Creation fails when dependent stack has protection 

### ISSUE THREAD

**Issue by sopeters** [cloudreach/sceptre#564]
When I launch or create a stack that has a dependency on another stack output (via !stack_output resolver) on a stack that has protect: true I get the error:

Cannot perform action on '<dependent stack>': Stack protection is currently enabled

How can I launch a stack with a reference to another protected stack?

**Comment by zaro0508** [comment]
This use case is not supported with sceptre core.  It will probably require a custom hook.  I would image that you can enumerate all the dependent stacks in the hook then turn off protection in a `before_create` or `before_update` hook call.  Once the stack is deployed you can turn protection back on in `after_create` or `after_update` hook call.  

```
hooks:
  before_create:
    - !stack_termination_protection 'disabled' 
  before_update:
    - !stack_termination_protection 'disabled' 
  after_create:
    - !stack_termination_protection 'enabled' 
  after_update:
    - !stack_termination_protection 'enabled' 
```

Take a look at https://github.com/zaro0508/sceptre-stack-termination-protection-hook to get started.  That hook currently only enables/disables protection on the current stack but it can probably be modified to do the same thing on a list of dependent stacks.
