### ISSUE TITLE
 Template format error: Unrecognized resource types: [AWS.yaml::EC2.yaml::InternetGateway]

### ISSUE THREAD

**Issue by jinwg** [cloudreach/sceptre#677]
Just upgraded from 1.x to 2.1.0 with python 3.6 this afternoon then met this weird issue. all generated resource types is not correct at all.   anyone met this problem?  
```
 VPC: 
        Type: AWS.yaml::EC2.yaml::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags: 
                - Key: Name 
                  Value: !Ref EnvironmentName
    VpcSecondaryCidrBlock:
        Type: AWS.yaml::EC2.yaml::VPCCidrBlock
        Properties:
          VpcId: !Ref VPC
          CidrBlock: !Ref SecondaryVpcCIDR

    InternetGateway:
        Type: AWS.yaml::EC2.yaml::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
```
