### ISSUE TITLE
sceptre generate dumps output in json escaped format when using j2 yaml templates

### ISSUE THREAD

**Issue by lukeplausin** [cloudreach/sceptre#708]
I'm not sure if this is a bug or the intended behaviour. When using sceptre to generate a template the output at the terminal does not match the output of the file which gets uploaded to S3.

Command:

` sceptre generate dev/mystack`

Expected result:

```yaml
---
# Clouformation template for some IAM roles.

Parameters:
  RoleLoginDurationSeconds:
      Type: Number
```

Actual result:

```['---\n# Clouformation template for some IAM roles. \n\nParameters:\n  RoleLoginDurationSeconds:\n    Type: Number...```

I am using jinja2 yaml templates on a windows machine.
