### ISSUE TITLE
filter 'default' does not correctly process empty values from stack_group_config.custom

### ISSUE THREAD

**Issue by oturpe** [cloudreach/sceptre#751]
In Sceptre 2.1.3, if I omit passing in a variable using the `--var` method and later pipe it to to a `default("")` filter, the end result is an empty string as expected. If I define a variable in stack group config's `custom` section and leave it empty, passing it to `default("")` produces value of `None`. It should be an empty string too.

## To reproduce
Simple CloudFormation template `templates/stack.yaml` that creates two log groups:
```
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LogGroupNameFromCustom:
    Type: String
  LogGroupNameFromVar:
    Type: String

Resources:
  LogGroupFromCustom:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /testing-sceptre/custom-${LogGroupNameFromCustom}
  LogGroupFromVar:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /testing-sceptre/var-${LogGroupNameFromVar}

```

Top level `config.yaml` specifying an empty custom variable:
```
project_code: testing-sceptre-none-behavior
region: eu-west-1
custom:
  suffix:
```

Only one stack configuration `config/app/stack.yaml`:
```
template_path: stack.yaml
parameters:
  LogGroupNameFromCustom: LogGroup{{ stack_group_config.custom.suffix | default("") }}
  LogGroupNameFromVar: LogGroup{{ var.suffix | default("") }}
```

Running `sceptre.exe launch --yes app`, the expected result is to have two log groups named like this:
1. _/testing-sceptre/var-LogGroup_
2. _/testing-sceptre/custom-LogGroup_

The observed result is that while the first one is correct, the second one has corrupted into form _/testing-sceptre/custom-LogGroupNone_

The real case where I ran into this had more complex setup of `custom` where a value was inferred from a var and could legitimately be empty.
