### ISSUE TITLE
Support UsePreviousValue in parameters

### ISSUE THREAD

**Issue by nathkc** [cloudreach/sceptre#77]
CD scripts can update e.g ECS image refs with CloudFormation's [UsePreviousValue](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html) flag. This ensures **only** the defined parameter is updated.

It'd be useful if Sceptre supported the same, to be sure we don't revert such changes on the next `update-stack`.

`cfn-sphere` has something similar in it's [KeepOrUse](https://github.com/cfn-sphere/cfn-sphere/wiki/StackConfig-Reference#keep-or-use-parameter-value) macro.

**Comment by nathkc** [comment]
Implementation-wise, could allow stack config parameters to accept dicts, e.g:

```yml
parameters:
  regular_style: 'my_value'
  verbose_style:
    value: 'my_value'
    use_previous_value: true
```

`Stack._format_parameters` would have to accept extra context, informing whether it's a create or update. If an update and `use_previous_value` is set, pass `{"ParameterKey": ..., "UsePreviousValue": true}` - otherwise, use the current behaviour.
