### ISSUE TITLE
Multi Region Stack Resolution

### ISSUE THREAD

**Issue by georgealton** [cloudreach/sceptre#85]
Part of my environment deploys 2 VPCs in eu-west-1 and 1 VPC in us-east-1. I'd then like to use a Route53 Hosted Zone to acts as a Globally resilient Private Hosted Zone for these VPCs. I have my root environment set up 

```
config/evertz
├── all
│   └── private-hosted-zone.yaml
├── config.yaml (region: eu-west-1)
├── region-1
│   ├── bastion.yaml
│   ├── config.yaml (region: eu-west-1)
│   ...
│   ├── vpc-peer.yaml
│   └── vpc.yaml
└── region-2
    ├── config.yaml (region: us-east-1)
    ...
    └── vpc.yaml 
```

The configuration of the private-hosted-zone stack is set up to use the resolver to retrieve the VPCID from the outputs of the stacks deployed in different regions 

```yaml
template_path: templates/PrivateHostedZone.yaml

parameters:
  Identifier: {{ var.identifier }}

  ZoneName: {{ var.zone_name }}

  VPCIds:
    - !stack_output evertz/region-1/vpc::VPCID
    - !stack_output evertz/region-1/vpc-peer::VPCID
    - !stack_output evertz/region-2/vpc::VPCID

  Regions:
    - {{ var.region_1 }}
    - {{ var.region_1 }}
    - {{ var.region_2 }}

  NumberOfVPC: '3'
```

However when attempting to resolve the stack name, it's unable to locate it, because I believe the stack I'm trying to resolve does not exist in the same region as the stack I'm deploying 

![cross_region_stacks](https://cloud.githubusercontent.com/assets/1202151/24511276/813dc2b8-1563-11e7-86f8-9df32fbe6384.png)

It would be awesome if the stack resolver looked the stack up in the region that stack was launched in, to help with multi region environments.
